<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sign in</title>
    <link href="style.css" rel="stylesheet">
</head>

<body>
    <?php
    if (!empty($_SESSION)) {
        include('includes/nav_logged.phtml');
    } else {
        include('includes/nav.phtml');
    }
    ?>
    <div id="container-form-signup">
        <h2>inscription</h2>
        <form action="login.php" method="post">
            <input type="text" placeholder="username" name="username">
            <input type="password" placeholder="password" name="password">
            <button type="input">sign up</button>
        </form>
    </div>
    <?php include('includes/footer.phtml'); ?>
</body>

</html>